################################################################################
# Game Control System Docker
################################################################################
# docker-compose up
################################################################################
version: "3.7"

services:
  logic:
    container_name: node-red
    image: ${REGISTRY:-docker.camart.co.uk:5000}/tpg22-control-build-logic:latest    
    restart: always
    environment:
      - TZ=Europe/London
      - NODE_RED_CREDENTIAL_SECRET      
    ports:
      - "7000:7000"
      - "8000:8000"
    networks:
      - topgolf
    volumes:
      - ${LOGIC_FLOW:-logic-flow}:/data/projects/logic
      - node-red-context:/data/context
      - ${LOGIC_CONFIG:-logic-config}:/data/config
      - ${LOGIC_CUSTOM:-logic-custom}:/data/custom 
      - ${SPEC_SOURCE:-api-spec}:/data/spec:ro
    extra_hosts:
      mqttbroker: ${MQTT_BROKER_IP:-host-gateway}
  app:
    container_name: app
    image: ${REGISTRY:-docker.camart.co.uk:5000}/tpg22-control-build-app:latest
    restart: always
    ports: 
      - "${APP_HTTP_PORT:-80}:80"
      - "${APP_HTTPS_PORT:-443}:443"
    networks:
      - topgolf  
    volumes: 
      - ${APP_SOURCE:-app-source}:/usr/share/nginx/html/client
      - ${SPEC_SOURCE:-api-spec}:/usr/share/nginx/html/spec
  prism:
    container_name: prism
    image: stoplight/prism:4
    restart: always
    command: 'proxy -h 0.0.0.0 /spec/api/gamelogic.openapi.yaml http://logic:1880/v1/'
    volumes:      
      - ${SPEC_SOURCE:-api-spec}:/spec:ro
    networks:
      - topgolf  
    ports:
      - "4010:4010"
  couchdb:
    container_name: couchdb
    image: couchdb
    restart: always
    volumes:
      - ./couchdb/:/opt/couchdb/etc/local.d
      - ${COUCHDB_DATA:-couchdb-data}:/opt/couchdb/data
    networks:
      - topgolf
    ports:
      - "5984:5984"
  ntp:
    image: cturra/ntp
    container_name: ntp
    restart: always
    ports:
      - 123:123/udp
    environment:
      - NTP_SERVERS=time.cloudflare.com
      - LOG_LEVEL=0
    networks:
      - topgolf
  mosquitto:
    container_name: mqtt
    restart: unless-stopped
    image: eclipse-mosquitto:2
    volumes:
      - ./mosquitto/:/mosquitto/config/:ro      
    ports:
      - 1883:${MOSQUITTO_PORT:-1883}
      - 9001:9001
    networks:
      - topgolf
volumes:
  logic-flow:
  node-red-context:
  logic-custom:
  logic-config:
  app-source:
  api-spec: 
  database:
  couchdb-data:
  couchdb-conf:
  
networks:
  topgolf:
