scrape_configs:
- job_name: cadvisor
  scrape_interval: 5s
  static_configs:
  - targets:
    - cadvisor:8080
- job_name: nodeexporter
  scrape_interval: 5s
  static_configs:
  - targets: 
    - nodeexporter:9100